### ISSUE TITLE
🗺️ LLM Application Tracing

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1000]
# Problem
In the modern AI stack, it's becoming common practice to build a **chain** of steps that execute a series of steps to generate a response (Think LangChain, LlamaIndex) Each one of these steps serves a different purpose: retrieval, embedding, generation etc. To best understand the output of a model, you no longer can just think of the model (LLM), you need to think of the problem end-to-end, you need to be able to monitor end-to-end. The introspection of the execution of an LLM Application will hereby be called a **trace**

## Milestone 1 - Tracing Views (Plumbing) - In Notebook
As an AI Engineer, I want to be able to understand how my generative application is running, specifically the parts (e.g. spans) that are running and the execution order. I want to be able to understand the parameters and the inputs / outputs of each **span** to uncover the black-box.

As an AI Engineer, I want to know what my application bottlenecks are, particularly around timing and token usage, these values should be propagated and aggregated for me so that I can better understand the possible UX implications of my App is.

Lastly, if certain components have exceptions, I want those surfaced early so I can correct them before I move my application to production.

This is critical because it requires 0 infrastructure and because I don't have to worry about sending my data to a 3rd party.

## Use-cases for generative apps
- RAG chat with my data
- Data agents like with LlamaIndex
- Agents

## Project Changes
To enable tracing, we need to be able to install sub-parts of the phoenix application. To begin with we should start with two components, the **app** and **tracer**
- [x] #1015

## Tracer
In order to collect traces from LLM frameworks we need to build a foundational `Tracer` that gets re-used across integrations.
- [x] #1002
- [x] #1004
- [x] #1017
- [x] #1018
- [x] #1019
- [x] #1068
- [x] #1078
- [x] #1079
- [x] #1152
- [x] #1150
- [x] #1151
- [x] #1311
- [x] #1415

## Server
- [x] #1033
- [x] #1036
- [x] #1032
- [x] #1037
- [x] [traces][gql] spans connection filters
- [x] #1070
- [x] #1045
- [x] #1062
- [x] #1069
- [x] #1087
- [x] [traces][gql] compute duration, add sort support for sorting
- [x] #1137
- [x] #1121
- [x] #1122
- [x] #1123
- [x] #1089
- [x] #1088
- [x] #1156
- [x] #1166
- [x] #1125
- [x] #1138
- [x] #1139
- [x] #1140
- [x] #1198

## UI
- [x] #1063
- [x] #1091
- [x] #1092
- [x] #1093
- [x] #1136
- [x] [traces][ui] Add duration and timestamp info to the span table
- [x] #1016
- [x] #1050
- [x] #1126
- [x] #1141
- [x] #1176
- [x] [traces][ui] span details on errors (events with exception)
- [x] #1190
- [x] #1191
- [x] #1157
- [x] #1167
- [x] #1260
- [x] #1261
- [x] #1195
- [x] [ui] span details view under trace
- [x] #1340
- [x] #1349
- [x] #1348
- [x] [traces][ui] tool details
- [x] #1492
- [x] #1493

## Integrations
[Integrations doc](https://docs.google.com/spreadsheets/d/1mQRoHuIpQdWFwTIEr4S6-nysVJVO6BlZPhr84saN0dA/edit#gid=0)
- [x] #921 
- [x] #1019  
- [x] #1056
- [x] #1057
- [x] #1077
- [x] #1081
- [x] #1090
- [x] #1080
- [x] #1127
- [x] LlamaIndex Tracing Callback
- [x] LangChain Tracing Callback
- [x] #1083
- [x] #1094
- [x] #1182
- [x] #1183
- [x] #1192
- [x] #1199
- [x] #1200
- [x] #1259
- [x] #1263
- [x] #1268
- [x] #1270
- [x] #1273
- [x] #1274
- [x] #1275
- [x] #1305
- [x] #1411
- [x] #1419

## Documentation
- [x] #1238
- [x] #1237
- [x] #1226
- [x] #1231
- [ ] #1416
- [x] #1417
- [x] #1418

## Events
- [x] #1456

## Post-launch cleanup

- [x] #1153
- [x] #1124
- [x] #1194
- [x] #1262
- [x] #1330
- [x] #1476

**Comment by mikeldking** [comment]
LLM Frameworks
- LangChain
- LlamaIndex
- Haystack (enterprise)

**Comment by mikeldking** [comment]
Failure modes
- rate limiting
- crashes
- function callback structure failure
- structured response parsing failure

**Comment by axiomofjoy** [comment]
add semantic attributes to langchain tracer

**Comment by axiomofjoy** [comment]
improve unit test coverage on llama index callback

**Comment by axiomofjoy** [comment]
enhance langchain error messages

**Comment by mikeldking** [comment]
Sub_question_query_engine might be missing a root span

**Comment by mikeldking** [comment]
RetrievalQAWithSourcesChain not working

**Comment by amank94** [comment]
RetrievalQAWithSourcesChain does not show underlying spans
Notebook: https://colab.research.google.com/drive/1HAqPbnSM5aj8C6QJQ8VGhT-Qink2she0?usp=sharing

Example screenshots
<img width="1512" alt="Screenshot 2023-09-25 at 4 02 19 PM" src="https://github.com/Arize-ai/phoenix/assets/12501961/cff39e16-eedd-4af8-b52c-5ba312634cd5">
<img width="1512" alt="Screenshot 2023-09-25 at 4 02 14 PM" src="https://github.com/Arize-ai/phoenix/assets/12501961/1a9cf6ea-1cb8-457d-92b4-0d63523e942d">

**Comment by mikeldking** [comment]
Closing as completed
