### ISSUE TITLE
🗺️ [tracing] Retrieval Evaluations

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1163]
## Milestone 2 - RAG Introspection
As an AI Engineer working on "chat with my data" - I want to know how documents are being retrieved and whether the right context is being retrieved. Notably I want to use the traces to make a decision about how to change my retrieval strategy. This might mean changing my embedding model, over-fetching documents and re-ranking, or even changing my embedding strategy (embed a summary, retrieve a full document).

The metrics we care about when it comes to retrieval are precision, and percent relevant (in some contexts known as `hit_rate`)

Since a RAG system typically lacks ground truth we will leverage an LLM to decide whether or not context is "relevant" or "not-relevant" which will be used to calculate the above metrics.

![image](https://github.com/Arize-ai/phoenix/assets/5640648/d1ee2455-112b-4a6b-9ded-beb971c37e6f)

- At a retriever span level, I, the AI engineer care about RAG Precision, and % relevant. These metrics will highlight spans that potentially are struggling to retrieve context - either due to a lack of data or other. I want a way to find these spans (sorting, filtering) and view the details as to why each document was relevant or irrelevant - causing the span level metric to degrade.
- At the application level, I, the AI engineer care about RAG precision and % relevant (`hit_rate`). This is important to me because I may want to adjust my retrieval strategy and re-run the application over a different strategy to see if these metrics improve. Examples of improving the application as a a whole are outlined above (chunking, embedding changes, metadata)
- At a trace level, I, the AI engineer care about RAG Precision, Precision @k, MRR, and % relevant 
- At a reranker span level, I the AI engineer care about RAG Precision, precision @k, and % relevant

# User Pain

As a AI engineer building out a retrieval augmented generative app, there is no way for me to identify specific queries that result in bad retrieval - notably when bad retrieval results in downstream consequences. These can be things like hallucinations, incorrect responses, or simply unsatisfactory answers. As an AI engineer, I want a tool that identifies bad RAG quality - at three different levels:

- document: is a document relevant to the question asked?
- retriever span: Is the retriever doing it's job of retrieving relevant content?
- trace: What are the queries that are resulting in poor retrieval? (partially related to the retriever quality)

As an AI engineer, I also want to incrementally improve my application's retrievals. Notably I may see a decline (either performance or user feedback) and deem it necessary to focus on adjusting the retrieval (and or data) to see if the generated responses improve. For this to be possible, Phoenix must provide top-level metrics for the application as a whole so that I can qualitatively say the new retrieval strategy (challenger) is better than the previous (champion). 

## Use-cases
- retrieval from a single vector store for summarization and or chat (stuff, map reduce etc.)
- retrieval over non vector stores (what does the corpus of data look like)
- use of a re-ranker to boost your relevancy (how should this impact overall relevancy metrics)

# Design
- [x] #1688

## Traces
- [x] #1548
- [x] #1691

## Evals
- [x] #1664
- [x] #1596
- [x] #1628
- [x] #1634
- [x] #1635
- [x] #1697
- [x] #1698
- [x] #1707
- [x] #1777
- [x] #1844
- [ ] [evals] capture directionality for our evaluation_criteria

## Server
- [x] #1701
- [x] #1655
- [x] #1636
- [x] #1776
- [x] #1843
- [x] #1842
- [x] #1875
- [x] #1881

## UI
- [x] #1639
- [x] [traces][ui] The ability to filter by evaluations
- [x] #2033
- [x] #1986
- [x] #1774
- [x] #1775
- [x] #1818
- [x] #1821
- [x] #1822
- [x] #1979
- [x] #1827
- [x] #1841
- [x] #1840
- [x] #2034

## Tracing
- [x] #1585

## Evaluators
- [x] #1706
- [x] #1737
- [x] #1752

## Persistence
- [x] #1972
- [x] #1998

# Documentation
- [ ] [evals] Notebook on how to evaluate traces
- [x] #1853
- [x] #1970
- [x] #1971
- [x] #2041
- [x] #2040
- [x] #2039
- [x] #2038

## Open Questions
- More than one index (e.x. llama_index data agents)
- What are the next steps to resolving a RAG problem (change chunking, multiple chunks, embed summary, embedding model, metadata, hyde, metadata, query parameters)
- Do we want to compute recall, F1 - but these lack the false negative 

## Resources
- Llama_Index RAG evals https://gpt-index.readthedocs.io/en/latest/examples/evaluation/retrieval/retriever_eval.html
