### ISSUE TITLE
🗺️ llama_index one-click solution

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1271]
As a user, I would like to be able to set a global callback handler for llama_index and get tracing out of the box.

# Documentation
- [x] #1435
- [x] #1428
- [x] #1429
- [x] #1434
- [x] #1433
- [x] #1432
- [ ] #1427
- [x] #1431
- [x] #1426
- [x] #1430

# Callback Enhancements
- [ ] #1437

# Llama_index
- [x] #1447
- [x] #1498

# Module re-factoring
- [x] #1325
- [ ] [traces] openInference tracer as a standalone moule

# Server
- [ ] [traces] place traces and trace datasets under subscriptions

# DX
- [x] #1326
# UI
- [ ] [traces] Switch traces listing to use a subscription
