### ISSUE TITLE
🗺️ [Evals] Promote evals out of experimental

### ISSUE THREAD

**Issue by anticorrelator** [Arize-ai/phoenix#2142]
@axiomofjoy and I made a small list of tasks we hoped to clean up before moving `evals` out of experimental

- [ ] control sync/async behavior with a flag: (sync/async/nest_async)
- [x] #2177
- [x] #2170
- [x] #2169
- [x] #2171
- [x] #2251
- [x] #2252
- [x] #2369
- [x] #2368

Should be installable via
```
pip install arize-phoenix[evals] 
``` 

## Documentation
- [x] #2372
- [x] #2370
- [x] #2371
- [x] #2373

# Follow-ups
- [x] #2356 
- [x] #2357 

# Open Questions
- Name of the package -> `arize-phoenix-evals`
- Repo organization, CI

# Migration Strategy
- [x] merge `packages/evals`
- [x] Move "new" ergonomic into new evals
- [x] publish `arize-phoenix-evals`
- [ ] write integration tests
- [x] Add `arize-phoenix-evals` as a dependency to phoenix
- [ ] ensure bridge still works under `experimental`
- [ ] Release 4.0

**Comment by anticorrelator** [comment]
This is done
