### ISSUE TITLE
🗺️ Tracing User Experience

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2596]
## Time
- [x] #5782
- [x] [UI] Time constraint (7D) on the Project Listing Page

## Tracing 
 - [ ] https://github.com/Arize-ai/phoenix/issues/2551
 - [x] #2622
 - [x] #2624
 - [x] #2069 
 - [x] #2625
 - [x] #3597 
 - [x] #5707

## Projects
- [x] #2539
- [x] #2540 
- [x] #2542
- [x] #2543
- [x] #2539
- [ ] https://github.com/Arize-ai/phoenix/issues/5973
- [x] #6095
- [ ] https://github.com/Arize-ai/phoenix/issues/6336
