### ISSUE TITLE
🗺 prompt playground

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3435]
As a user of Phoenix I don't want to have to go back to my IDE to iterate on a prompt. I want to be able to use the data stored in Phoenix (spans, dataets) and run them through a prompt.

## Use-cases
- Replay a template change on an LLM Span
- Run a template change on a dataset
- Construct an evaluation template on a single chosen production span or Dataset - Workflow is testing your Evals and be able to save as experiment
- Synthetic data Generation - Use to generate synthetic data, add columns to current rows of data in a dataset, to help create test data 

## Milestone 1 - LLM Replay
The most important thing to accomplish is the ability to take a specific LLM step (e.g. a span) and to be able to re-play that execution. In the process of re-executing that step, we should record the new response so that we can compare and evaluate.

Leads: @axiomofjoy @anticorrelator 

**Out of Scope**
- focus on Chat Completions (things with roles) - not completions

### Planning
- [x] #4658
- [x] #4600

### UI
- [x] #4606
- [x] #4885
- [x] #4857
- [x] #4886
- [x] #4887
- [x] #4888
- [x] #4889
- [x] #4890
- [x] #4996
- [x] #5092
- [x] #4891
- [x] #4892
- [x] #4902
- [x] #5183
- [x] #4949
- [x] #4952
- [x] #4953
- [x] #4986
- [x] #4987
- [x] #4997
- [x] #4998
- [x] #5041
- [x] #5020
- [x] #5023
- [x] #5034
- [x] #5040
- [x] #5181
- [x] #5182
- [x] #5069
- [x] #5036
- [x] #5035
- [x] #5099
- [x] #5100
- [x] #5112
- [x] #5209
- [x] #5210
- [x] #5233
- [x] #5252
- [x] #5253
- [x] #5267
- [x] #5353

### API
- [x] #4773
- [x] #4774
- [x] #4858
- [x] #4859
- [x] #4793
- [x] #4856
- [x] #4893
- [x] #4894
- [x] #4900
- [x] #5093
- [x] #4901
- [x] #4895
- [x] #4897
- [x] #5154
- [x] #5091
- [x] #4960
- [x] #4975
- [x] #4989
- [x] #4988
- [x] #4990
- [x] #4995
- [x] #5030
- [x] #4930
- [x] #5031
- [x] #5037
- [x] #5038
- [x] #5039
- [x] #5097
- [x] #5116
- [x] #5160
- [x] #5187

## Testing
- [x] #4962
- [x] #4984

## Fix
- [x] #4983
- [x] #5075
- [x] #5126
- [x] #5317

### Instrumentation
- [x] #5101
- [x] #4896
- [x] #4904
- [x] #4908
- [x] #5194
- [x] #5195
- [x] #5102
- [x] #5311
- [x] #5312
- [x] #5369
- [x] #5370 

### OpenIneference
- [x] https://github.com/Arize-ai/openinference/issues/1109

## Milestone 2 - Datasets on Playgrounds

Add support to run a set of dataset examples through a prompt

### API

- [x] #5238
- [x] #5241
- [x] #4804
- [x] #5261
- [x] #5276
- [x] [playground][datasets] ensure experiment runs are created for template formatting errors 
- [x] #5294
- [x] #5313

### UI
- [x] #4803 - this contains a rough list of todos
- [x] #5281
- [x] #5282
- [x] #5283
- [x] #5284
- [x] #5285
- [x] #5286
- [x] [playground][datasets] ensure experiment runs are created for template formatting errors 
- [x] #5300
- [x] #5304
- [x] #5328 

## Milestone 3 - Playground run annotations and evaluators
Add support for easily annotating playground runs via human annotations or evaluators.
Note: Annotations for playground spans is already supported as of the milestones above

## Dogfooding
- [x] #5373
- [x] #5402 
- [x] #5443
- [x] #5444
- [x] #5448

#### UI
- [x] #5370
- [x] #5369
- [x] #5286
- [x] #5284
- [x] #5267
- [x] #4886 - missing prompt template variable parsing
- [x] #5382
- [x] #5383
- [x] #5384
- [x] #5385
- [x] #5386
- [x] #5387
- [x] #5388
- [x] #5411
- [x] #5431

#### Azure
- [x] #5413

#### Anthropic
- [x] #5405
- [x] #5406
- [x] #5409

#### Server
- [x] #5389
- [x] #5390
- [x] #5391
- [x] #5392
- [x] #5394

### Dogfooding issues round 2
- [x] #5459
- [x] #5460
- [x] #5461
- [x] #5454
- [x] #5462
- [x] #5455
- [x] #5456
- [x] #5457
- [x] #5458
- [x] #5463
- [x] #5464
- [x] #5465
- [x] #5466
- [x] #5528
- [x] #5533
- [x] #5534

## Presentations
- [x] #5474

## Documentation
- [x] #5568
- [x] [playground][docs] how to section on playground (e.g. compare)

## Post-Launch
- [x] #5483
- [x] #5484
- [x] #5485
- [x] #5530
- [x] #5393
- [x] #5489
- [x] #5516
- [x] #5393

## Punt

- [x] #5303 
- [x] #5350
- [x] #5410
- [x] #5407
- [x] #5427

**Comment by heralight** [comment]
Hi!

## Enhancement proposal
This feature should be similar to #2462 but with more depth. It would involve a simple button to replicate a query into an edit mode, allowing you to replay it. Additionally, it should offer the possibility to add notes on the result iterations, such as rating the quality, format output, etc., on a scale of 1 to 10.

## Goal
The goal is to facilitate quick testing of prompts and inputs, enabling evaluation and visualization of progression.

Thank you,

Alexandre

**Comment by mikeldking** [comment]
> Hi!
> 
> 
> 
> ## Enhancement proposal
> 
> This feature should be similar to #2462 but with more depth. It would involve a simple button to replicate a query into an edit mode, allowing you to replay it. Additionally, it should offer the possibility to add notes on the result iterations, such as rating the quality, format output, etc., on a scale of 1 to 10.
> 
> 
> 
> ## Goal
> 
> The goal is to facilitate quick testing of prompts and inputs, enabling evaluation and visualization of progression.
> 
> 
> 
> Thank you,
> 
> 
> 
> Alexandre

@heralight Hey! Thanks for the feedback! We have a ton of features coming out with regards to prompt iteration, notably prompt experiments. Stay tuned. It has evaluations built in 

Noted on the replay and the annotations:) will give it some thought. We have a few ideas around replaying data at prompts, but haven't thought about human annotations on different prom versions a ton. Would love to hear more.

**Comment by heralight** [comment]
Very nice!
my ideal workflow, would be:
- trace some openai calls made from code
- transform some into a replayable prompt, where each modification can be tested and versioned and annoted  and ranked.
- prompt can parametized and call from code

best,

**Comment by axiomofjoy** [comment]
🛝🎉
