### ISSUE TITLE
🗺️ Embeddings: point groups and coloring

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#354]
## Color by feature / tag / actual
As a user, I need the ability to use color to distinguish different characteristics of the model events (UMAP points). These can be inherent characteristics of the events (dimensions), performance metrics of the events (correctness, confusion matrix)

### Backend
- [x] #257

### App
- [x] [point-cloud] Color by numeric dimension
- [x] #355
- [ ] [point-cloud] Color by Confusion Matrix
- [x] [point-cloud] Color by predictions
- [x] [point-cloud] [drift] Color by dataset
- [x] [point-cloud] Color by categorical features
- [x] [point-cloud] Color by numeric ranges
