### ISSUE TITLE
🗺️ Docs Refresh

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#4090]
## Onboarding
- [ ] [docs] Arize Phoenix landing page
- [ ] [docs] Improved README
- [ ] [docs] navigate to specific quickstarts

## Organization
- [x] #4110
- [ ] End-to-end navigation for experiments
- [ ] Promote integrations higher in tracing
- [ ] Move concepts lower
- [ ] Shorten overview sections
- [x] #4349
- [x] #4105
- [x] #4109
- [ ] [docs] Javascript quickstart

# Self-hosting
- [ ][docs] configuration of self-hosting
- [ ][docs] quickstart for self-hosting

## Examples
- [ ] [docs] distinction between application examples, cook books

## Runnable Quickstarts
- [x] #4510
- [ ] [docs] runnable quickstart for tracing

## Hosted Phoenix
- [x] #4348
- [ ] [docs] Updated LlamaIndex Tracing notebook for hosted phoenix
- [ ] https://github.com/Arize-ai/phoenix/issues/4509

## Evals
- [x] #4092
- [x] #4097
- [x] #4307
- [ ] #6065

## Tracing
- [x] #4911
- [ ] #6691
- [x] #6689
- [ ] [docs] simplified quickstart that is framework agnostic
- [ ] [docs] features section
- [ ] [docs] how to use gRPC to export
- [ ] #6597 
- [x] #6690
- [ ] #6650
- [ ] #6651

## Prompt Enginering
- [x] #6652

## TypeScript
- [x] #6692

**Comment by mikeldking** [comment]
closing this in favor of smaller tickets.
