### ISSUE TITLE
🗺 Prompt Management

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#5582]
As teams grow, it can become important to track and manage prompts independently from code for re-use inside of Phoenix and other integration points like evaluation.

Phoenix prompts will let you find, create, modify, and version control prompts for and LLMs in general.

# Technical requirements

- Prompts should be versioned
- Prompts should be provider independent
- Prompts should be cashable for high availability (both server side and client side)

# Spike
- [x] #5604
- [x] #5676
- [x] [hub][spike] flesh out prompt management use-cases and data model
- [x] [hub][spike] caching of prompt templates
- [x] #5677
- [x] [hub][spike] prompt template model configuration tracking
- [x] #5625
- [x] #5719
- [x] [hub][spike] zod types for messages, tools, output_schema
- [x] #5737
- [x] #6137

# Technical Infra
- [x] #5684 

# Server
- [x] #5733
- [x] [hub] [gql] prompt listing
- [x] #5762
- [x] #5754
- [x] #5753
- [x] #5743
- [x] #5732
- [x] #5801
- [x] #5778
- [x] #5800
- [x] #5799
- [x] #5771
- [x] #5798
- [x] #5763
- [x] #5764
- [x] #5779
- [x] #5795
- [x] #5796
- [x] #6042
- [x] #5788
- [x] #5797
- [x] #5846
- [x] #5848
- [x] #5866
- [x] #5880
- [x] #5883
- [x] #5884
- [x] #5887
- [x] #5895
- [x] #5900
- [x] #5909
- [x] #5906
- [x] #5908
- [x] #5910
- [x] #5930
- [x] #5931
- [x] #5939
- [x] #5947
- [x] #5952
- [x] #5953
- [x] #5969
- [x] #5972
- [x] #5987
- [x] #6019
- [x] #6020
- [x] #6021
- [x] #6022
- [x] #6032
- [x] #6078
- [x] [api] [hub] Prevent prompt updates when no changes are made
- [x] [api] [hub] Add ability to trace/span output back to dataset
- [ ] #6138
- [x] #6080
- [x] #6168
- [x] #6151
- [x] #6195
- [x] #6197

### Prompt Details / Management
- [x] #5725
- [x] #5741
- [x] #5735
- [x] #5736
- [x] #5734
- [x] #5759
- [x] #5761
- [x] #5760
- [x] #5777
- [x] #5776
- [x] #5863
- [x] #5864
- [x] #5865
- [x] #5932
- [x] [hub] [ui] prompt version tag edit (description at least)
- [x] [hub] [ui] ability to tag a version on the prompt history
- [x] [hub] [ui] prompt clone
- [x] [hub] [ui] prompt tags in prompt aside
- [x] #5970
- [x] [hub] [ui] delete a prompt
- [x] #6317
- [ ] #6169
- [x] #6114
- [x] #6061
- [x] #6058
- [x] #6092
- [x] #6059
- [x] #6060
- [x] #6072
- [x] #6074
- [x] #6089
- [x] #6105
- [x] #6151

## Prompt Tagging / Version Management

- [x] #5966

###  Prompt Editor / Playground
- [x] #5879
- [x] #5881
- [x] #5882
- [x] #5886
- [x] #5923
- [x] #5924
- [x] #6334

# Tracing
- [x] #6152

# Analytics
- [ ] [hub] scope out prompt template analytics

# Python SDK
- [x] #5997
- [x] #5996

# TypeScript SDK
- [x] #5998
- [x] #5999
- [x] #6000

# Testing
- [x] #6344
- [ ] #6345

# Documentation
- [x] #5967
- [x] #5968
- [ ] #6231
- [ ] #6232
- [ ] #6172
- [x] #6173
- [ ] #6381

# Bugs
- [x] #6369
- [x] #6368
- [ ] #6367
- [ ] #6366
- [x] #6365
- [x] #6394
