### ISSUE TITLE
🗺 search and retrieval

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#815]
As an application builder, I want to be able to extend my LLM's capabilities using external or private data using a vector DB (such as pinecone).

Cases where I need an external DB are (in order of precedence):
- Internal knowledge base
- Up-to-date data to accomidate for lack of training data with the LLM
- Grounding the LLM in a context so it's less likely to hallucinate (steering via context and few shot learning)
- LLM Memory for agents 

In order to evaluate the performance / quality of the overall system, a few heuristics are emerging:

- Quality of the knowledge base
     - Is there enough data to answer the questions?
     - Is the knowledge base properly indexed? What embeddings are used?
     - Using sparse vs dense representations?
     - Are the documents properly sanitized?
     - Are the documents chunked correctly?
     - Are the parameters sent to the vector DB tuned well for proper retrieval?
 - Quality of my prompts
     - Does the prompt improve / degrade the quality of the overall system?
 - Quality of the application
     - The ways in which retiereval is chained and piped into the LLM can matter 
  - End-user satisfaction
     - Did the user like the response? (thumbs_up)  
  -  Business satisfaction (KPIs)
     - Did the application cause more human intervention and escalations?
     - Is the chat bot saving money via automation
     
 To evaluate such a system, phoenix needs to be able to surface problems using opinionated heuristics:
- Identify cohorts of queries that lack context 
- Identify cohorts of queries that get the wrong context
- Identify cohorts that get badly prioritized context
- Identify cohorts that are causing dissatisfaction by a real user
- Identify cohorts that are deemed bad via LLM assisted evals or evaluation metrics
- Map queries back to the context that was used so you can audit the retrieval system

To better understand systems such as the above, we need to be able to dogfood and test hypothesis against a system

# Relationships
As a user, I want to be able to correlate an inference to other inferences / embeddings

wireframe: https://app.excalidraw.com/s/AtcpXqHEPnG/2hjNqfvyP6I

- [x] #877
- [x] #878
- [x] #900
- [x] #901
- [x] #898
- [x] #879
- [x] #897
- [x] #927
- [x] #928

# Corpus Datasets
As a user for search and retrieval, I would like to be able to ingest corpus records and launch phoenix without having to overload the reference dataset.

- [x] #894
- [x] #899
- [x] [gql] [retrieval] constext dataset resolver under query to let UI know that context exists
- [x] [gql] [retrieval] refactor UMAP points to support loading in context projections
- [x] [gql] [retrieval] fetching of individual context records via a unique ID
- [x] [core] [retrieval] mapping user-generated IDs to graphQL unique IDs 
- [x] [ui] Add a "third" dataset visibility toggle
- [x] [ui] refactor all dataset role parsing
- [ ] [ui] split the grid view into model events and context records
- [ ] [ui] split the list view into model events and context records
- [x] #942
- [x] [ui] context details slide over
- [x] #943
- [x] #958

# Workshops / use-cases
- [x] #869
- [x] #870
- [x] #930

# Documentation
- [x] #932
- [x] #933
- [x] #959
- [x] #980

**Comment by Parker-Stafford** [comment]
Dataset sample size is not indicative of number of context points
- only affects primary, was slightly confusing for me at first
- wanted to get a slightly less dense point cloud so tried lowering the sample size and it didn't look much different
-  makes sense to show all of context but may be nice to call that out somewhere
- low priority

![image](https://github.com/Arize-ai/phoenix/assets/52351508/9e513720-a8cc-4466-a0cc-f891352afe01)

**Comment by mikeldking** [comment]
> Dataset sample size is not indicative of number of context points
> 
> * only affects primary, was slightly confusing for me at first
> * wanted to get a slightly less dense point cloud so tried lowering the sample size (a little hard to grok the topology when there are so many points) and it didn't look much different
> * makes sense to show all of context but may be nice to call that out somewhere
> * low priority

Thanks @Parker-Stafford - definitely something I believe we will have to prioritize. It's a bit of a hard problem as right now we think "more" is better to paint the right picture. Making it guaranteed that the points referenced in the retrievals are guaranteed to not be sampled could be something we could think about.

But @RogerHYang was definitely looking for ergonomic feedback on the corpus - so thanks for flagging!

**Comment by mikeldking** [comment]
As flagged by @axiomofjoy - you can't select Query Distance again once you deviate from that selection.

**Comment by axiomofjoy** [comment]
The sampling strategy we currently use for corpus data points needs to be improved.

**Comment by axiomofjoy** [comment]
Add option to center embedding vectors in the Phoenix UI.

**Comment by axiomofjoy** [comment]
Add experiment sub-module.

**Comment by axiomofjoy** [comment]
Add LLM-assisted ranking metrics to `experimental` sub-module.

**Comment by axiomofjoy** [comment]
Create scripts for generating RAG fixtures

**Comment by axiomofjoy** [comment]
Add support for arbitrary edge metadata

**Comment by axiomofjoy** [comment]
Enable coloring by edge metadata.

**Comment by axiomofjoy** [comment]
Highlight point in the point cloud when I hover over the card in the cluster details panel.

**Comment by axiomofjoy** [comment]
Two-minute elevator pitch video

**Comment by axiomofjoy** [comment]
SuperAGI hackathon workshop

**Comment by axiomofjoy** [comment]
ODSC RAG workshop

**Comment by mikeldking** [comment]
Closing to reset for 2024
