### ISSUE TITLE
🗺️ LLM framework integrations

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#907]
Acceptance criteria
- [ ] as a user, I can find sufficient documentation within phoenix docs to create a callback and launch phoenix
- [ ] as a non-arize user, I can use langchin or llama_index in my notebook and an launch phoenix with LLM records without having to write monkey patches or sub-classes

langchain
- [x] #925
- [ ] #926
- [ ] #908
- [x] #1011

llama_index
- [x] #921 
- [x] #922
- [x] #923
- [ ] #967
- [x] #924
- [x] #1009

file-system writes
- [x] write out LLM records to a file and persist

notebook re-factoring
- [ ] add evaluator prompt to experimental sub-module
- [ ] add de-biasing to experimental sub-module

documentation
- [x] #931
- [x] #966

Phoenix
- [x] #963
- [x] #964

**Comment by mikeldking** [comment]
blockers for langchain
- [ ] no embeddings callback
- [ ] retrieval scores not returned in any callback hooks
- [ ] document IDs from the vector DB not returned

**Comment by mikeldking** [comment]
closing as completed
